title: RakiBlogs
description: > # this means to ignore newlines until "baseurl:"
  Welcome to RakiBlogs, blogs related to crypto and other stuff that you may need it.
  It cover a wide vareity of topics from Blockchain,
  Artificial Intelligence, to Aerospace engineering.

permalink: ':title/'
# baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "https://nsdffd.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Rakib Fiha # add your name
author-img: rakib-fiha.jpg # add your photo
about-author: Hey there! I'm <a href="https://RakibFiha.com">Rakib Fiha</a>. <br> <br> Welcome to RakiBlogs!! <br><br> I will try to cover as much as I can to write about Blockchain, AI and also the projects that I am currently working on. I am mainly writing these blogs for me, so that I can come back here and see how's things going. haha. <br> <br> But at the same time, anyone is welcome to join me here. <br> <br> <a href="https://RakibFiha.com"> Here </a> you can know more about me. # add description
social-twitter: RakibFiha # add your Twitter handle
social-facebook: RakibFiha # add your Facebook handle
social-github: RakibFiha # add your Github handle
social-linkedin: RakibFiha # add your Linkedin handle
social-email: mrahman06@qub.ac.uk # add your Email address

# Disqus
discus-identifier: RakibFiha # add your discus identifier

# Tracker
analytics: Rakib Fiha # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  # - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
