name: rakiBlog
description: >
    A simple jekyll theme aimed at programmers who like clean interface to write posts
    and show off some code.
about: >
    This is my blog site. If you are here and would like to know about me then press the link below.
master_repo: false
url: "http://vinitkumar.me/white-paper"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 5

logo:             https://raw.githubusercontent.com/RakibFiha/RakibFiha.github.io/master/R.png
disqus_shortname:

rtl: false
owner:
  name:           Rakib Fiha
  avatar:         "https://avatars1.githubusercontent.com/u/15315703?s=400&v=4"
  email:          "mrahman06@qub.ac.uk"
  # Social networking links used in footer. Update and remove as you like.
  twitter: RakibFiha
  twitterabt: https://twitter.com/RakibFiha
  github: https://github.com/RakibFiha
  stackexchange: https://stackoverflow.com/users/9496100/rakib-fiha
  linkedin: https://www.linkedin.com/in/RakibFiha
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
